### ISSUE TITLE
Fallo en tests 'Capítulo 01'

### ISSUE THREAD

**Issue by Neoterux** [DAWFIEC/DAWM-2022#1]
Los test de los ejercicios 5 y 6 fallan debido a que se eliminan los espacios en el resultado esperado, pero el contenido no se eliminan espacios.

### **Article**
Error:
`let articleClean = article.replace(/(\r\n|\n|\r)/gm, '').replace(/ /g, '')`
Solucion:
`let articleClean = article.replace(/(\r\n|\n|\r)/gm, '')`
Para que concuerde con la eliminación de los espacios en la respuesta del servidor.

### Archivos con el error

* Ejercicio 5
    * test/article.test.js
* Ejercicio 6
    * test/document.test.js
    * test/media.test.js
    * test/object.test.js

**Comment by aavendan** [comment]
Resuelto
